workspace(name = "rules_rllvm_examples")

local_repository(
    name = "rules_rllvm",
    path = "..",
)

load("@rules_rllvm//toolchain:deps.bzl", "rules_rllvm_dependencies")

rules_rllvm_dependencies()

load("@rules_rllvm//toolchain:rules.bzl", "rllvm_toolchain")

rllvm_toolchain(
    "rllvm_toolchain",
    llvm_version = "19.1.0",
    rllvm_log_level = 5,
    skip_bitcode_generation = True,
)

register_toolchains("@rllvm_toolchain//:all")
